### ISSUE TITLE
met problem when test on my dataset 

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [DenisVorotyntsev/AutoSeries#1]
I make a [dataset](https://github.com/ComplicatedPhenomenon/16) which has the same feature as your dataset `data/15/`,  there is no problem when I tested on dataset `14` and `15`, yet when I tested on my dataset, it throws `'IndexError: single positional indexer is out-of-bounds`, 

![Screenshot from 2020-03-10 21-26-56](https://user-images.githubusercontent.com/24690806/76396984-3f45f080-63b5-11ea-826c-0f4db9f7a57b.png)

I can not see the difference in format between my dataset with dataset `15` , Would you please give me some clue? Thanks.

**Comment by DenisVorotyntsev** [comment]
It's obviously some problem during updating of the model, I spent some time, but didn't find it. I recommend to turn off updating by changing: 
```
if self.n_predict > self.update_interval:
    next_step = 'predict'  # before: "update"
    self.n_predict = 0
else:
    next_step = 'predict'
```
in `model.py`.
